# Copyright (C) 2016-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (C) 2016-present Sven Greb <development@svengreb.de>

# Project:    Nord Atom UI
# Repository: https://github.com/arcticicestudio/nord-atom-ui
# License:    MIT
# References:
#   https://docs.travis-ci.com

language: objective-c
notifications:
  email:
    on_success: never
    on_failure: change
script: "curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh"
