#!/bin/bash
curl -s https://api.coinbase.com/v2/prices/BTC-EUR/buy | cut -d\: -f5 | cut -d\" -f2 | sed 's/...$//' | sed 's/\B[0-9]\{3\}\>/,&/'
#curl -s http://api.coindesk.com/v2/bpi/currentprice.json  | jq '.bpi.EUR.rate' | curl -s http://api.coindesk.com/v2/bpi/currentprice.json  | jq '.bpi.EUR.rate' | sed 's/^.//' | sed 's/......$//'
